project:
  type: website
  output-dir: docs

website:
  title: "BAN 300 - F24"
  sidebar:
    style: "docked"
    search: true
    contents:
      - syllabus.qmd
      - schedule.qmd
      - bookmarks.qmd
      - section: "Labs"
        contents:
          - href: ./labs/lab01.qmd
            text: Lab 1
      - section: "Assignments"
      - section: "Training Projects"
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true